services:
  # Zookeeper est nécessaire pour gérer le cluster Kafka
  zookeeper:
    image: zookeeper:3.9.2
    ports:
      - "2181:2181"

  # Le broker Kafka pour l'ingestion temps réel
  kafka:
    image: bitnamilegacy/kafka:3.7.0
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      # Configuration réseau importante : permet l'accès depuis l'intérieur (Spark/Airflow) et l'extérieur (Scraper python local) de Docker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
    ports:
      - "9093:9093"
    depends_on:
      - zookeeper

  # La base de données relationnelle cible (utilisée dans ton DAG Airflow)
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=finance_news
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Le Data Lake pour stocker l'historique des news (S3 local)
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    ports:
      - "9000:9000" # Port API (Spark lira ici)
      - "9001:9001" # Port Console (Interface Web)

  # --- Apache Airflow (Orchestration) ---
  airflow-init:
    image: apache/airflow:2.9.1
    depends_on:
      - postgres
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/finance_news
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    # Initialise la base de données et crée un utilisateur admin/admin
    command: >
      bash -c "airflow db migrate && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com"

  airflow-webserver:
    image: apache/airflow:2.9.1
    depends_on:
      - airflow-init
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/finance_news
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - _PIP_ADDITIONAL_REQUIREMENTS=kafka-python requests beautifulsoup4 lxml
      - KAFKA_BROKER=kafka:9092
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scrapers:/opt/airflow/scrapers
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.9.1
    depends_on:
      - airflow-init
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/finance_news
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      # Installation des librairies pour faire fonctionner ton scraper dans le conteneur
      - _PIP_ADDITIONAL_REQUIREMENTS=kafka-python requests beautifulsoup4 lxml
      - KAFKA_BROKER=kafka:9092
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scrapers:/opt/airflow/scrapers
    command: scheduler

volumes:
  pgdata: